CHANGELOG.md, doc/fparser.rst, src/fparser/block_statements.py, src/fparser/tests/test_functional.py
This PR is for work done in #31. It simply makes SpecificBinding a valid declaration entity and add a functional test for this. I've also taken the opportunity to make fparser print a useful message if it fails to parse something. All tests pass or xfail. (All PSyclone tests pass or xfail with this version too.)
=> Allow for Procedure declarations

CHANGELOG.md, src/fparser/Fortran2003.py, src/fparser/tests/fparser2/test_base_classses.py, src/fparser/tests/test_Fortran2003.py
This PR is for #34 and fixes fparser's assumption that a second, positional item in an IO control list is always a Format (it may be a namelist).
=> Fix for namelist/format specifier confusion

src/fparser/statements.py, src/fparser/tests/test_parser.py
accepted. Added test case for usage of '::", and also test cases
for module procedure declaration without the (optional) 'module'.
=> Fix #45: The optional '::' in a module procedure declaration was not

src/fparser/Fortran2003.py, src/fparser/tests/fparser2/test_Fortran2003.py
This PR fixes #36 by correcting the `match` method of `Connect_Spec`.
=> #36 fix missing unit number for open statements

src/fparser/tests/test_parser.py
Hi,
nothing particularly smart, but I copied the integer declaration test cases to test real, double precision, complex, double complec, logical, and byte.
Also: the import from block_statement is confusing - that only worked because at the bottom(!) of block_statement is: 
```
from statements import *
from typedecl_statements import *
```
I've started to move some of the imports to be from the right module.
=> Added tests  for complex, double complex, logical, real etc

src/fparser/readfortran.py, src/fparser/splitline.py, src/fparser/tests/test_parser.py, src/fparser/tests/test_splitline.py
Hi,
this fixes lines like "integer a(3) = [1,2,3]". The parser didn't like the [] ('(/ /)' worked), and I also improved handling of quotes in case of assignment of arrays of strings.
=> Declaration with array assignment

src/fparser/readfortran.py, src/fparser/sourceinfo.py, src/fparser/tests/test_sourceinfo.py
This change is a precursor to allowing `FortranFileReader` to accept a file object as well as a filename.
Now the "source info" functions called by that class can accept a file object.
In order to try and ensure I did not change functionality I also added a suite of unit tests. I also took the opportunity to reduce code duplication.
I have tried this new version of fparser against the head of the PSyclone trunk and have two failures although it's not obvious that they were caused by this change. I seem to get the same two failures when running with the head of fparser trunk.
=> Improve "source info" functions and add testing

CHANGELOG.md, src/fparser/Fortran2003.py, src/fparser/api.py, src/fparser/base_classes.py, src/fparser/block_statements.py, src/fparser/parsefortran.py, src/fparser/readfortran.py, src/fparser/scripts/f2003.py, src/fparser/scripts/parse.py, src/fparser/sourceinfo.py, src/fparser/tests/test_base_classes.py, src/fparser/tests/test_parsefortran.py, src/fparser/tests/test_parser.py, src/fparser/tests/test_readfortran.py, src/fparser/tests/test_select.py, src/fparser/tests/test_sourceinfo.py
This change allows the Fortran reader to operate on an already open file-like object as well as on a filename which it opens itself. This is to ease life for users of the fparser library.
I have also spread the use of the FortranFormat object created in my previous branch into the file reader. This just encapsulates a lot of knowledge about Fortran source formats. It also corrals some of the less well understood aspects of the library. Such as what "fix" and "pyf" are.
Given that I always get hit up for this anyway I've also run pycodestyle over a number of big files and dealt with the result. Note I haven't used pylint as that runs headlong into a lot of legacy issues. I hope that can be left for another day.
=> Fortran file reader now takes a file-like object as well as a filename

CHANGELOG.md, src/fparser/one/block_statements.py, src/fparser/one/tests/test_block_stmts.py, src/fparser/one/typedecl_statements.py
Small code fix and added new test for the associated routine.
=> For #81 - fix undefined variable in get_type_by_name()

CHANGELOG.md, doc/fparser.rst, setup.py, src/fparser/two/tests/test_Fortran2003.py, src/fparser/two/tests/test_fortran2003.py
This PR is for issue #95 and contributes to eventually closing #91. 
I did some more clean-up than modifications mentioned in the issue text - summary below:
- Removed dependence on `nose` (replaced `assert_equal` with `assert`),
- Renamed invalid variables (e.g. `a`, `s`) to improve `pylint` score,
- Removed capitalisation from test names and disabled `invalid-name` warning only for tests with very long names (`pylint`),
- Removed some duplicate tests and `redefined-variable` warnings (`pylint`),
- Unified existing docstrings.
P.S. Updated `setup.py` and documentation to remove dependency on `nose`.
=> Improve test_Fortran2003.py

src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_name_r304.py, src/fparser/two/tests/test_fortran2003.py
If we provide an name with internal spaces we now get an error. e.g.
```
program a a
end program
```
will now produce a syntax error.
=> names with spaces now raise an exception. #112

CHANGELOG.md, doc/fparser2.rst, src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_program_r201.py, src/fparser/two/utils.py
The parser now returns with no error if the input file is empty or only contains white space and/or newlines, rather than raising a SyntaxError or falling over in a heap. Whilst it is probably correct to raise a SyntaxError, a number of compilers allow empty input without complaining so we follow their lead.
=> Support Empty input files

CHANGELOG.md, src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_derived_type_stmt_r430.py, src/fparser/two/tests/test_fortran2003.py
Improves the implementation and tests for derived_type_stmt fortran2003 rule 430. Also fixes the reported bug.
=> Derived type stmt error

.gitignore, .travis.yml
Removed the triggering of coveralls from travis. Also added .egg-info to gitignore as suggested in PR #142.
=> Remove coveralls

CHANGELOG.md, src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_executable_construct_r213.py
PR for issue #147 originally provided as a fix in PR #142. This is a simple fix that changes the name of one of the subclasses so that it is now uses the correct rule. I've added associated tests and tidied the class. One of these tests xfails (for a forall loop) and I've added a new issue for this. However, I think this is one of the fixes also found in #142. I've also removed a spurious reference to the Comment class as it is never used (as comments are dealt with in BlockBase).
=> Executable construct bug

CHANGELOG.md, src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_executable_construct_r213.py, src/fparser/two/tests/fortran2003/test_forall_header_r754.py, src/fparser/two/tests/test_fortran2003.py
Fixes various errors in the fortran 2003 forall header rule r754 and adds appropriate tests.
=> Forall header bug fix

src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_primary_r701.py, src/fparser/two/tests/test_fortran2003.py
Closes #167
The order defined by R701 wasn't honoured in ``subclass_names``, hence ``fparser.two`` was trying to recursively parse the contents of the brackets *before* it could figure out that it should try treating the expression as an array assignment.
Happy to add a test if desired. It would look like adding a large-ish source file with 400+ reals in an array. I figured that the order of the subclass_names shouldn't now change, so was 50/50 as to whether a test was really needed.
=> Fix parsing of large arrays

src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_main_program_r1101.py, src/fparser/two/tests/fortran2003/test_program_r201.py, src/fparser/two/tests/fortran2008/test_end_submodule_stmt_r1119.py, src/fparser/two/tests/fortran2008/test_program_unit_r202.py, src/fparser/two/tests/fortran2008/test_submodule_r1116.py, src/fparser/two/tests/test_fortran2003.py, src/fparser/two/tests/test_parser.py, src/fparser/two/utils.py
Currently ``fparser.two`` automatically names end statements based on their counterpart "start" statements.
It also automatically injects statement type information into the parsed End statement object. This essentially means that we are preventing a round-trip of the original code, and even though it is desirable to have as much context as possible in the outputted source, it is problematic to achieve correctly and questionable as to whether it should be done *at parse time*. This was discussed in https://github.com/stfc/fparser/pull/186#issuecomment-477638184. I propose that similar automatic-naming functionality be restored as an (optional) *post-processing* step on the parse-tree, rather than a parse-time manipulation (though not in this PR).
=> Remove automatic naming of End statements

CHANGELOG.md, src/fparser/common/sourceinfo.py, src/fparser/common/tests/test_sourceinfo.py, src/fparser/common/tests/test_utils.py, src/fparser/common/utils.py
As mentioned earlier in today's telco, under certain conditions (py>2,<py3.7, non-unicode terminal) the *existing* tests do not pass.
```
pytest common/tests/test_utils.py
================================================================ test session starts =================================================================
platform linux -- Python 3.5.6, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
rootdir: /data/local/itpe/fparser, inifile:
plugins: xdist-1.26.1, forked-1.0.2
collected 12 items                                                                                                                                   
common/tests/test_utils.py .........FFF                                                                                                        [100%] …
```
=> Changes needed to get the tests passing with python3.6 on an ASCII terminal.

CHANGELOG.md, src/fparser/common/readfortran.py, src/fparser/common/tests/test_readfortran.py
I believe this is the final change needed in fparser to handle unicode comments from ASCII terminals, as was being seen when running ``psyclone ${LFRIC}/miniapps/skeleton/working/unit-tests/algorithm/slow_physics_alg_mod.x90 -d ${LFRIC}/gungho/source/kernel/``. That particular invocation of psyclone was resulting in the kernel not being found once the unicode handling had been fixed by #194: 
```
Error, unexpected exception, please report to the authors:
Description ...
list index out of range
Type ...
<class 'IndexError'>
Stacktrace ...
File "/data/local/itpe/PSyclone/src/psyclone/generator.py", line 396, in main
kern_naming=args.kernel_renaming)
File "/data/local/itpe/PSyclone/src/psyclone/generator.py", line 222, in generate
line_length=line_length)
File …
```
=> Fix unicode handling of FortranFileReader, as used by PSyclone.

CHANGELOG.md, src/fparser/two/tests/test_fortran2003.py
Currently there is no testing for end statements for types with multiple spaces in them (applies to "BLOCK DATA").
The code that will need testing/fixing is at https://github.com/stfc/fparser/blob/fc79f65/src/fparser/two/utils.py#L1188.
=> WIP: Addition of a EndStmtBase test case using 'block data' which currently fails

.travis.yml, CHANGELOG.md
If we can get this working, then a rich unicode terminal will be just fine.
Hopefully, this will demonstrate the tests that are currently failing on master with ``LANG=ascii``.
Once #194 is merged, I will rebase this and the CI should go green. :tada:
=> WIP: Enable a limited terminal in the Travis testing

setup.py
Console script entry point for `fparser2.py` will be installed, such that user can invoke the script with simply:
```bash
fparser2 program.f90
```
This is especially useful if the user has installed fparser from pypi and might not know where the script is installed.
=> install fparser2 script entry point

src/fparser/two/Fortran2003.py
Intrinsic function `IBITS(I, POS, LEN)` should expect exactly 3 arguments, fparser required it to have exactly 2.
Reference: https://j3-fortran.org/doc/year/04/04-007.pdf#page=312
Page 312, Line 24
=> Changed number of expected arguments for intrinsic function IBITS to 3

CHANGELOG.md, src/fparser/two/pattern_tools.py
=> #245 Fix python deprecation warnings caused by RE strings.

CHANGELOG.md, src/fparser/common/readfortran.py, src/fparser/common/tests/test_readfortran.py
This is the implementation following the discussion in #248. It should successfully identify any line with '#' as first non-white space character as a cpp directive. For such cases, a new `CppDirective` subclass of `Line` is returned instead.
I suggest merging this before #239 as it allows to identify cpp directives more easily.
Documentation will be updated as part of #239.
=> Add detection and dedicated type for Cpp directives to readfortran

CHANGELOG.md, src/fparser/two/C99Preprocessor.py, src/fparser/two/tests/test_c99preprocessor.py
Small fix for an error in the regex responsible for matching the identifier list in the definition of PP macros. This prohibited matching arguments that are longer than 1 character.
The test base was amended accordingly.
=> Fix matching of multichar arguments in PP macro identifier lists

CHANGELOG.md, src/fparser/common/utils.py
fixes #271 - uses UTF-8 encoding in `module_in_file()` to allow non-Unicode locales
=> 271 read using UFT8 encoding

src/fparser/one/tests/test_parsefortran.py
This PR aims to improve test reliability of test `test_log_empty` by resetting `FortranParser.cache` and `log` to the initial state by calling method `log.reset` and `cache.clear` respectively.
The test can fail in this way by running `pip3 install pytest-repeat; python3 -m pytest --count=2 src/fparser/one/tests/test_parsefortran.py::test_log_empty`:
```
>       assert log.messages == {'debug':    [],
'info':     ['Nothing to analyze.'],
'warning':  [],
'error':    [],
'critical': []}
E       AssertionError: assert {'critical': ...alyze.'], ...} == {'critical': [...alyze.'], ...}
E         Omitting 4 identical items, use -vv to show
E         Differing items:
E         {'info': ['using cached thingumy', 'Nothing to analyze.']} != {'info': ['Nothing to analyze.']}
```
It may be better to …
=> Resetting `FortranParser.cache` and `log` to the initial state

CHANGELOG.md, src/fparser/two/Fortran2003.py, src/fparser/two/Fortran2008.py, src/fparser/two/tests/fortran2008/test_type_declaration_stmt_r501.py
For F2008 support, `Type_Declaration_Stmt` is overwritten to use the modified `Attr_Spec_List`. Accordingly, symbol table entries have to be added there as well. To avoid code duplication, I have moved the relevant check into a method of the F2003 class and call this in both implementations.
=> Create symbol table entries also for F2008 Type_Declaration_Stmt (fixes #316)

CHANGELOG.md, example/README.md, example/create_dependencies.py
This is a small improvement to the Fortran dependency creation to support files in subdirectories, e.g.:
```
field/integer_field_mod.o: constants_mod.o count_mod.o field/field_parent_mod.o \
field/pure_abstract_field_mod.o function_space_mod.o log_mod.o mesh_mod.o \
mpi_mod.o
```
I.e. the subdirectories are added where applicable (this shows work in progress with the PSyclone LFRic infrastructure files, where only one subdirectory, ``field``, has been created - i.e. all other files are indeed still in the base directory).
=> #362 Dependency example: support files in subdirectories.

src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_format_item_list.py, src/fparser/two/tests/fortran2003/test_format_item_r1003.py, src/fparser/two/tests/test_fortran2003.py
This fixes parsing of hollerith items in `format-items` in three cases:
- Omitted comma before a hollerith item: `/3Habc`
- Omitted comma after a hollerith item: `3Habc/`
- Trailing whitespace in trailing hollerith item: `4Hspc `
It also changes `Format_Item_List` to match single item lists rather than bail out and rely on `Format_Item`. This matches the behavior of `SequenceBase` and all the generated lists.
=> Fix parsing of format-items with hollerith items and omitted commas

CHANGELOG.md
My contributions to fparser fall under a mission from my company,
Bull S. A. S.; before some boss comes around and scolds me, it's best if 
my company name appears after my name :)
=> Fix associated organisation in changelog

src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_format_item_r1003.py, src/fparser/two/tests/utils/test_bracket_base.py, src/fparser/two/utils.py
Such trailing whitespace is important for `Hollerith_Item`s which may occur at the end of a `Format_Item_List` and require trailing whitespace.
This actually fixes `BracketBase` consuming trailing whitespace anywhere. I believe this is fine because all the `match` implementations I've seen strip their input before processing.
=> Fix trailing whitespace being lost when Format_Item_List is in parentheses

CHANGELOG.md, src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_cray_pointer_decl.py, src/fparser/two/tests/fortran2003/test_hollerith_item.py, src/fparser/two/tests/fortran2003/test_position_edit_desc_r1013.py, src/fparser/two/tests/fortran2003/test_rename_r1111.py, src/fparser/two/tests/fortran2003/test_usestmt_r1109.py, src/fparser/two/tests/test_fortran2003.py
This is a towards since it just fixes the crash in the symbol table. It does not attempt to extend the symbol table to support operators.
=> (Towards #379) ensure symbol table cleanly ignores operators

CHANGELOG.md, doc/source/fparser2.rst, src/fparser/two/Fortran2008.py, src/fparser/two/tests/fortran2008/test_procedure_stmt_r1206.py, src/fparser/two/tests/test_fortran2003.py
Adds support for the F2008 R1206 procedure_stmt rule:
`procedure-stmt is [ MODULE ] PROCEDURE [ :: ] procedure-name-list`
which differs slightly from the F2003 R1206 rule by allowing optional '::':
`procedure-stmt is [ MODULE ] PROCEDURE procedure-name-list`
=> add f2008 R1206 procedure-stmt support (closes issue 405)

CHANGELOG.md, doc/source/fparser2.rst, src/fparser/two/Fortran2003.py, src/fparser/two/Fortran2008.py, src/fparser/two/tests/fortran2003/test_loop_control_r830.py, src/fparser/two/tests/fortran2008/test_loop_control_r818.py, src/fparser/two/tests/test_fortran2003.py
Replaces PR #404 to provide a complete implementation where the matching to `do concurrent` is limited to f2008 code (f2003 will not match). Also adds appropriate f2008 tests, pulls out and extends the existing f2003 tests and updates the f2003 implementation.
To add in the matching to `do concurrent` I have changed the tuple that is returned by a match in f2003. This will affect any tools that walk the fparser2 tree structure. The first argument is now a string which specifies the type of match "WHILE" or "COUNTER". In the f2008 match "CONCURRENT" is also allowed. The second argument returns the classes resulting from matching and the third argument returns the optional delimiter. The reason for adding the first argument string is that it helps a tree traversal/transformation tool to …
=> add support for f08 do concurrent (closes #403)

CHANGELOG.md, src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_namelist_stmt_r552.py, src/fparser/two/tests/test_fortran2003.py
The implementation of namelist-stmt r552 in Fortran2003 (Namelist_Stmt) contained asserts in two places rather than returning None (which specifies no match). This PR fixes this error, tidies the code, tightens the implementation and adds tests that fully cover the code in the class.
=> Fix namelist r552 matching error (closes #165)

CHANGELOG.md, src/fparser/common/readfortran.py, src/fparser/common/tests/test_readfortran.py, src/fparser/two/tests/test_utils.py
Currently the reader reverses the lines it returns for an include file. This happens if a match fails and read lines are pushed into the FIFO. This PR is a small fix which just ensures that such lines are pushed into the FIFO of the current reader object rather than the top-level one.
=> (Closes #412) fix reader for include files

CHANGELOG.md, src/fparser/two/Fortran2008/Fortran2008.py, src/fparser/two/Fortran2008/__init__.py, src/fparser/two/parser.py, src/fparser/two/tests/fortran2008/test_submodule_stmt_r1117.py
To split the Fortran2008.py file into a file per class we also need to create an __init__ file within a Fortran2008 directory that allows us to import the Fortran2008 classes as if they were in a single file and generate any required files there as well. This PR does this first part and moves the Fortran2008.py file into the Fortran2008 directory. A subsequent PR will actually split the Fortran2008 file.
=> use __init__ to import Fortran2008 classes (towards #411)

CHANGELOG.md, src/fparser/one/block_statements.py, src/fparser/one/tests/test_where_construct_stmt_r745.py
The fix is a one line change as we just need to return the original value of the string expression (using 'map'), rather than the string expression itself (F2PY_EXPR_TUPLE_1). For the example shown in issue #430:
```
subroutine columnwise_op_asm_m2v_lumped_inv_kernel_code()
where (columnwise_matrix(:,:,cell) /= 0.0_r_solver)
columnwise_matrix(:,:,cell) = 1.0_r_solver/columnwise_matrix(:,:,cell)
end where
end subroutine columnwise_op_asm_m2v_lumped_inv_kernel_code
```
We used to get ...
```
!BEGINSOURCE
SUBROUTINE columnwise_op_asm_m2v_lumped_inv_kernel_code()
WHERE ( F2PY_EXPR_TUPLE_1 )
columnwise_matrix(:,:,cell) = 1.0_r_solver/columnwise_matrix(:,:,cell)
END WHERE
END SUBROUTINE columnwise_op_asm_m2v_lumped_inv_kernel_code
```
But now get ....
```
!BEGINSOURCE
SUBROUTINE …
```
=> fparser1 where statement bug fix (closes #430)

.github/workflows/unit-tests.yml, CHANGELOG.md, doc/source/conf.py, doc/source/examples.rst, doc/source/index.rst, doc/source/license.rst, example/Makefile, example/make_public.py, example/split_file.py, example/test_files/create_dependencies/correct_dependencies, example/test_files/make_public.f90, example/test_files/make_public_correct.f90, example/test_files/split_file/test.f90
Adds a script that removes all private and protected attributes (which is used in PSyclone's kernel extraction).
Added a chapter explaining the examples to the manual, added tests for examples (triggered in CI), and added me as author.
=> 448 make public example

CHANGELOG.md, doc/source/developers_guide.rst, doc/source/fparser2.rst, src/fparser/two/Fortran2003.py, src/fparser/two/Fortran2008/__init__.py, src/fparser/two/Fortran2008/stop_code_r857.py, src/fparser/two/tests/fortran2008/test_stop_code_r857.py, src/fparser/two/tests/test_fortran2003.py, src/fparser/two/utils.py
Fixes #320. Adds support for extended stop codes to Fortran 2003, and adds full 2008 support for (even more) flexible expressions.
I hope I did the 2008 part correctly. I esp. wasn't certain how to check if the expressions are constant :(
=> (Closes #320) nonstandard stop

.gitignore, CHANGELOG.md, src/fparser/common/utils.py, src/fparser/two/Fortran2003.py, src/fparser/two/tests/test_parser.py, src/fparser/two/utils.py
=> Allow deepcopy of fparser tree

CHANGELOG.md, src/fparser/common/tests/test_readfortran.py, src/fparser/common/tests/test_sourceinfo.py
Use pytest tmpdir (which is cleaned up automatically), instead of /tmp for temporary files (over 220 files per test run). Fixes #454.
=> #454 Create file in pytest's tmpdir, not in /tmp.
