src/fparser/statements.py
Very simple regex fix so that all tests now pass or xfail.
=> #7 Fix regex bug in Entry match expression

README.md
Add badges for Coveralls (code coverage) and Landscape (code style/correctness) to the README.md.
=> Add coverage and 'health' (landscape) badges.

setup.py
A two-line change and one of those is simply adding a new-line to the end of a file :-)
=> #16 Add numpy and nose as dependencies

.gitignore, CHANGELOG.md, src/fparser/Fortran2003.py, src/fparser/splitline.py, src/fparser/tests/test_Fortran2003.py
I've just checked this code with a version of Habakkuk that has had the built-in fparser code stripped out. All tests passed.
=> Merge-in bug fixes performed during Habakkuk development.

CHANGELOG.md
In the brave new world of github it's not entirely clear to me when we should update the changelog, especially since we've locked the master branch. Probably we should do it immediately prior to merging a pull request? I'd forgotten to do that for both the Habakkuk fixes (#10) and documentation (#2) so this pull request is simply to update the changelog file appropriately.
=> Update changelog following #2 and #10 being done.

CHANGELOG.md, doc/fparser.rst, src/fparser/tests/test_parser.py, src/fparser/typedecl_statements.py
This pull request resolves issue #27.
=> Bugfix - ensure class(my_class) is not re-generated as class(kind=my_class)

.travis.yml, doc/conf.py, src/fparser/Fortran2003.py, src/fparser/api.py, src/fparser/base_classes.py, src/fparser/block_statements.py, src/fparser/parsefortran.py, src/fparser/pattern_tools.py, src/fparser/readfortran.py, src/fparser/scripts/f2003.py, src/fparser/scripts/parse.py, src/fparser/scripts/read.py, src/fparser/sourceinfo.py, src/fparser/splitline.py, src/fparser/statements.py, src/fparser/tests/fparser2/test_Fortran2003.py, src/fparser/tests/test_api.py, src/fparser/tests/test_blank_lines.py, src/fparser/tests/test_issue11.py, src/fparser/tests/test_issue25.py, src/fparser/tests/test_issue26.py, src/fparser/tests/test_issue33.py, src/fparser/tests/test_issue5.py, src/fparser/tests/test_issue7.py, src/fparser/tests/test_mod_private.py, src/fparser/tests/test_parser.py, src/fparser/tests/test_select.py, src/fparser/tests/test_utils.py, src/fparser/typedecl_statements.py, src/fparser/utils.py
As discussed in #43, I moved the code base to Python3 and restored compatibility to Python2.7 afterwards. I therefor relied on the unit tests, so there might be still some problems hidden in uncovered areas.
=> Move to py3

src/fparser/tests/test_parser.py
(except missing docstrings).
At least a small start ;)
=> Made test_parse.py pep8 compliant, and fixed most pylint messages

src/fparser/api.py, src/fparser/base_classes.py, src/fparser/parsefortran.py, src/fparser/readfortran.py, src/fparser/tests/test_parser.py
Some minor modification so that a user gets better error message (esp. in psyclone - instead of just "Is the Fortran correct").
=> Add better error messages in case of some parsing problems.

CHANGELOG.md, src/fparser/statements.py, src/fparser/tests/test_parser.py
This PR is for #76 - handle allocates using names of derived types as type specifiers.
=> Allocate type

CHANGELOG.md, src/fparser/two/Fortran2003.py, src/fparser/two/tests/test_Fortran2003.py
This change tackles issue #83.
=> Completes procedure prefix list.

CHANGELOG.md, src/fparser/two/Fortran2003.py, src/fparser/two/pattern_tools.py, src/fparser/two/tests/test_Fortran2003.py, src/fparser/two/tests/test_comments.py, src/fparser/two/tests/test_deferred_method.py
This PR makes fparser2 pycodestyle compliant. It makes no functional changes to fparser.
=> Fparser2 pycodestyle issue #89

CHANGELOG.md, doc/developers_guide.rst, doc/fparser2.rst, src/fparser/scripts/fparser2.py, src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_kind-selector_r404.py, src/fparser/two/tests/fortran2003/test_kindselector_r404.py, src/fparser/two/tests/test_fortran2003.py, src/fparser/two/tests/test_scripts.py, src/fparser/two/utils.py
Includes new exception and its use in a class. If this looks reasonable then I suggest we follow this approach for the other classes (as we modify them).
Also added an x-failing test in the wrong file (r404) as the error happens there (but due to errors earlier).
=> Kind error fix issue #110

CHANGELOG.md, doc/fparser2.rst, src/fparser/two/tests/test_utils.py, src/fparser/two/utils.py
Adds the get_child() utility from Habakkuk.
=> Add get_child() utility

CHANGELOG.md, doc/developers_guide.rst, doc/fparser2.rst, src/fparser/common/base_classes.py, src/fparser/common/readfortran.py, src/fparser/common/tests/test_readfortran.py, src/fparser/one/parsefortran.py, src/fparser/tests/test_issue11.py, src/fparser/two/Fortran2003.py, src/fparser/two/pattern_tools.py, src/fparser/two/tests/fortran2003/test_include_filename.py, src/fparser/two/tests/fortran2003/test_include_statement.py, src/fparser/two/tests/fortran2003/test_program_r201.py, src/fparser/two/tests/utils/test_blockbase.py, src/fparser/two/utils.py
=> Support include statements

src/fparser/two/Fortran2003.py, src/fparser/two/tests/fortran2003/test_main_program_r1101.py, src/fparser/two/tests/utils/test_blockbase.py, src/fparser/two/utils.py
=> Enforce strict ordering of main program.

CHANGELOG.md, src/fparser/common/readfortran.py, src/fparser/common/tests/test_readfortran.py, src/fparser/two/C99Preprocessor.py, src/fparser/two/tests/test_scripts.py
Fixes the bug reported in #262.
=> eof error (closes #262)

CHANGELOG.md, example/Makefile, example/README.md, example/create_dependencies.py, example/fparser2_f2008.py, example/test_files/a.f90, example/test_files/b.f90, example/test_files/c.f90
Fixes #274 - adds the example of dependency creator for makefiles.
=> #274 Added script to output makefile-dependencies for Fortran modules.

CHANGELOG.md, src/fparser/two/Fortran2003.py, src/fparser/two/Fortran2008.py, src/fparser/two/parser.py, src/fparser/two/tests/fortran2003/test_if_stmt_r807.py, src/fparser/two/tests/fortran2008/test_action_stmt_r214.py, src/fparser/two/tests/fortran2008/test_error_stop_stmt_r856.py, src/fparser/two/tests/fortran2008/test_if_stmt_r837.py
This adds support for F2008's `ERROR STOP` stmt.
=> Add F2008 Error_Stop_Stmt with tests (fixes #314)

.github/workflows/unit-tests.yml, CHANGELOG.md, src/fparser/__init__.py, src/fparser/common/splitline.py, src/fparser/one/tests/test_scripts.py, src/fparser/one/tests/test_select.py, src/fparser/tests/test_fparser_module.py
@arporter @sergisiso @hiker Small change to bump python version.
=> (Closes #470) python version bump
